#!/usr/bin/env bash

elementIn () {
    local e match="$1"
    shift
    for e; do [[ "$e" == "$match" ]] && return 0; done
    return 1
}

if [ -z "$1" ] ; then
    echo "No argument supplied"
    exit
fi

echo "Executing command..."
scripts=(export manage install)
if elementIn "$1" "${scripts[@]}"; then
    echo "Executing ./bash/$1.sh"
    eval "./bash/$1.sh ${@:2}"
else
    echo "Pleas specify command (export, manage, utility)"
fi
