version: '2.3'

services:
    docker-registry-repo:
        container_name: docker-registry-repo
        image: registry:2
        restart: always
        ports:
            - ${DOCKER_REGISTRY_PORT}:5000
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${DOCKER_REGISTRY_PATH}:${DOCKER_REGISTRY_PORT}.crt
            REGISTRY_HTTP_TLS_KEY: /certs/${DOCKER_REGISTRY_PATH}:${DOCKER_REGISTRY_PORT}.key
        volumes:
            - ./data/registry:/var/lib/registry
            - ./data/auth:/auth
            - ./data/cert:/certs
