version: '2.3'

services:
    portainer:
        container_name: portainer
        image: portainer/portainer
        restart: always
        ports:
            - ${PORTAINER_PORT}:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data
